const logoMonnaies = {
    Afghanistan: 'AFN',
    'Afrique du Sud': 'ZAR',
    Albanie: 'ALL',
    Algérie: 'DZD',
    Allemagne: 'EUR',
    Andorre: 'EUR',
    Angola: 'AOA',
    'Antigua-et-Barbuda': 'XCD',
    'Arabie Saoudite': 'SAR',
    Argentine: 'ARS',
    Arménie: 'AMD',
    Australie: 'AUD',
    Autriche: 'EUR',
    Azerbaïdjan: 'AZN',
    Bahamas: 'BSD',
    Bahreïn: 'BHD',
    Bangladesh: 'BDT',
    Barbade: 'BBD',
    Belgique: 'EUR',
    Bélize: 'BZD',
    Bénin: 'XOF',
    Bhoutan: 'BTN',
    Bélarus: 'BYN',
    Birmanie: 'MMK',
    Bolivie: 'BOB',
    Bosnie-Herzégovine: 'BAM',
    Botswana: 'BWP',
    Brésil: 'BRL',
    Brunei: 'BND',
    Bulgarie: 'BGN',
    Burkina-Faso: 'XOF',
    Burundi: 'BIF',
    Cambodge: 'KHR',
    Cameroun: 'XAF',
    Canada: 'CAD',
    Cap-Vert: 'CVE',
    'République centrafricaine': 'XAF',
    Chili: 'CLP',
    Chine: 'CNY',
    Chypre: 'EUR',
    Colombie: 'COP',
    Comores: 'KMF',
    'République du Congo': 'XAF',
    'République démocratique du Congo': 'CDF',
    'Îles Cook': 'NZD',
    'Corée du Nord': 'KPW',
    'Corée du Sud': 'KRW',
    'Costa Rica': 'CRC',
    'Côte d’Ivoire': 'XOF',
    Croatie: 'HRK',
    Cuba: 'CUP',
    Danemark: 'DKK',
    Djibouti: 'DJF',
    'République dominicaine': 'DOP',
    Dominique: 'XCD',
    'Égypte': 'EGP',
    Émirats Arabes Unis: 'AED',
    Équateur: 'USD',
    Érythrée: 'ERN',
    Espagne: 'EUR',
    Estonie: 'EUR',
    Eswatini: 'SZL',
    États-Unis: 'USD',
    Éthiopie: 'ETB',
    Fidji: 'FJD',
    Finlande: 'EUR',
    France: 'EUR',
    Gabon: 'XAF',
    Gambie: 'GMD',
    Géorgie: 'GEL',
    Ghana: 'GHS',
    Grèce: 'EUR',
    Grenade: 'XCD',
    Guatemala: 'GTQ',
    Guinée: 'GNF',
    'Guinée-Bissau': 'XOF',
    'Guinée Équatoriale': 'XAF',
    Guyana: 'GYD',
    Haïti: 'HTG',
    Honduras: 'HNL',
    Hongrie: 'HUF',
    Inde: 'INR',
    Indonésie: 'IDR',
    Irak: 'IQD',
    Iran: 'IRR',
    Irlande: 'EUR',
    Islande: 'ISK',
    Israël: 'ILS',
    Italie: 'EUR',
    Jamaïque: 'JMD',
    Japon: 'JPY',
    Jordanie: 'JOD',
    Kazakhstan: 'KZT',
    Kenya: 'KES',
    Kirghizistan: 'KGS',
    Kiribati: 'AUD',
    Koweït: 'KWD',
    Laos: 'LAK',
    Lesotho: 'LSL',
    Lettonie: 'EUR',
    Liban: 'LBP',
    Liberia: 'LRD',
    Libye: 'LYD',
    Liechtenstein: 'CHF',
    Lituanie: 'EUR',
    Luxembourg: 'EUR',
    Macédoine: 'MKD',
    Madagascar: 'MGA',
    Malaisie: 'MYR',
    Malawi: 'MWK',
    Maldives: 'MVR',
    Mali: 'XOF',
    Malte: 'EUR',
    Maroc: 'MAD',
    'Îles Marshall': 'USD',
    Maurice: 'MUR',
    Mauritanie: 'MRU',
    Mexique: 'MXN',
    Micronésie: 'USD',
    Moldavie: 'MDL',
    Monaco: 'EUR',
    Mongolie: 'MNT',
    Monténégro: 'EUR',
    Mozambique: 'MZN',
    Namibie: 'NAD',
    Nauru: 'AUD',
    Népal: 'NPR',
    Nicaragua: 'NIO',
    Niger: 'XOF',
    Nigéria: 'NGN',
    'Niue': 'NZD',
    Norvège: 'NOK',
    Nouvelle-Zélande: 'NZD',
    Oman: 'OMR',
    Ouganda: 'UGX',
    Ouzbékistan: 'UZS',
    Pakistan: 'PKR',
    Palaos: 'USD',
    Palestine: 'TBD',
    Panama: 'PAB',
    'Papouasie-Nouvelle-Guinée': 'PGK',
    Paraguay: 'PYG',
    Pays-Bas: 'EUR',
    Pérou: 'PEN',
    Philippines: 'PHP',
    Pologne: 'PLN',
    Portugal: 'EUR',
    Qatar: 'QAR',
    Roumanie: 'RON',
    Royaume-Uni: 'GBP',
    Russie: 'RUB',
    Rwanda: 'RWF',
    'Saint-Christophe-et-Niévès': 'XCD',
    'Sainte-Lucie': 'XCD',
    'Saint-Marin': 'EUR',
    'Saint-Vincent-et-les-Grenadines': 'XCD',
    'Îles Salomon': 'SBD',
    Salvador: 'SVC',
    Samoa: 'WST',
    'São Tomé-et-Principe': 'STN',
    Sénégal: 'XOF',
    'Serbie': 'RSD',
    Seychelles: 'SCR',
    'Sierra Leone': 'SLL',
    Singapour: 'SGD',
    Slovaquie: 'EUR',
    Slovénie: 'EUR',
    Somalie: 'SOS',
    Soudan: 'SDG',
    'Soudan du Sud': 'SSP',
    'Sri Lanka': 'LKR',
    Suède: 'SEK',
    Suisse: 'CHF',
    Suriname: 'SRD',
    Syrie: 'SYP',
    Tadjikistan: 'TJS',
    Tanzanie: 'TZS',
    Tchad: 'XAF',
    Tchéquie: 'CZK',
    Thaïlande: 'THB',
    'Timor oriental': 'USD',
    Togo: 'XOF',
    Tonga: 'TOP',
    'Trinité-et-Tobago': 'TTD',
    Tunisie: 'TND',
    Turkménistan: 'TMT',
    Turquie: 'TRY',
    Tuvalu: 'AUD',
    Ukraine: 'UAH',
    Uruguay: 'UYU',
    Vanuatu: 'VUV',
    Vatican: 'EUR',
    Venezuela: 'VES',
    Vietnam: 'VND',
    'Yémen': 'YER',
    Zambie: 'ZMW',
    Zimbabwe: 'ZWL',
};
